### ISSUE TITLE
GitHub.VisualStudio.Views.GitHubPane.GitHubPaneView”时引发了异常。 ---> System.IO.IOException: 找不到资源“views/githubpane/githubpaneview.xaml”。

### ISSUE THREAD

**Issue by maikebing** [maikebing/VisualStudio#1]
Microsoft.VisualStudio.Composition.CompositionFailedException: 参初始化部件“GitHub.VisualStudio.Views.GitHubPane.GitHubPaneView”时引发了异常。 ---> System.IO.IOException: 找不到资源“views/githubpane/githubpaneview.xaml”。
   在 MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   在 System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   在 System.IO.Packaging.PackagePart.GetStream()
   在 System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   在 GitHub.VisualStudio.Views.GitHubPane.GitHubPaneView.InitializeComponent() 位置 D:\Works\GitHub\VisualStudio\src\GitHub.VisualStudio\Views\GitHubPane\GitHubPaneView.xaml:行号 1
   在 GitHub.VisualStudio.Views.GitHubPane.GitHubPaneView..ctor(INotificationDispatcher notifications) 位置 D:\Works\GitHub\VisualStudio\src\GitHub.VisualStudio\Views\GitHubPane\GitHubPaneView.xaml.cs:行号 26
   --- 内部异常堆栈跟踪的结尾 ---
   在 Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   在 Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   在 Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   在 Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   在 Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   在 Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass13_0.<CreateExportFactory>b__0()
   在 Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   在 Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   在 System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   在 GitHub.Factories.ViewViewModelFactory.CreateView(Type viewModel) 位置 D:\Works\GitHub\VisualStudio\src\GitHub.App\Factories\ViewViewModelFactory.cs:行号 47
   在 GitHub.Factories.ViewViewModelFactory.CreateView[TViewModel]() 位置 D:\Works\GitHub\VisualStudio\src\GitHub.App\Factories\ViewViewModelFactory.cs:行号 40
   在 GitHub.VisualStudio.UI.GitHubPane.<InitializeAsync>d__12.MoveNext() 位置 D:\Works\GitHub\VisualStudio\src\GitHub.VisualStudio\UI\GitHubPane.cs:行号 107

**Comment by maikebing** [comment]
@heku  你能帮忙看看吗？

**Comment by heku** [comment]
不好意思，整个周末都在加班，最近非常忙，我看close了，已经解决了是吧？

**Comment by maikebing** [comment]
@heku  不过遇到新问题了， 菜单始终出不来， 我对比了CodeMaid 你的方法， 始终不行， 不知道是不是我进了某种误区了。 要是有空， 帮忙看看。

**Comment by maikebing** [comment]
这个issue 的解决方法是翻看你的 项目解决的。

**Comment by heku** [comment]
好，今晚下班回去我看下。

**Comment by heku** [comment]
今晚网络很差，源码中的那几个submodule下到现在都没下下来，只能改天再看了。

**Comment by maikebing** [comment]
有空么？

**Comment by heku** [comment]
最近每天都要凌晨后下班。。。看这周末要不要加班了吧，不要的话有时间。抱歉啊！

**Comment by maikebing** [comment]
忙了好， 不像我， 最近闲的发疯。

**Comment by heku** [comment]
几个submodule死活下不下来，所以整个项目我跑不起来。通过看代码，感觉可能会有问题的点：
* InlineReviews.csproj 这个应该有问题，缺少`<ResourceName>Menus.ctmenu</ResourceName>`
```xml
    <VSCTCompile Include="InlineReviewsPackage.en-US.vsct" />
    <VSCTCompile Include="InlineReviewsPackage.zh-Hans.vsct" />
```
* GitHub.VisualStudio.csproj 中下面这些被删掉了，我不太确定这有没有影响。
```xml      
<IncludeOutputGroupsInVSIX>BuiltProjectOutputGroup;GetCopyToOutputDirectoryItems;DebugSymbolsProjectOutputGroup;</IncludeOutputGroupsInVSIX>
<IncludeOutputGroupsInVSIXLocalOnly>DebugSymbolsProjectOutputGroup;</IncludeOutputGroupsInVSIXLocalOnly>
```
* 这是个多project的vs plugin，我之前写的都是单project的，不太确定是不是所有project都要改成
```csharp
[assembly: NeutralResourcesLanguage("en-US", UltimateResourceFallbackLocation.Satellite)]

<UICulture>en-US</UICulture>
```
但当前我发现你有的项目改了这些，有的没有改，不知道是你就是这么改的，还是有部分改漏了。

以上不一定能有用，你要试了没用的话还请见谅。

**Comment by maikebing** [comment]
有邮箱吗？我给你发过去？

**Comment by maikebing** [comment]
最近闲了吗？  @heku
